name: Deploy expense system to aws

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.x
      - name: set up terraform
        uses: hashicorp/setup-terraform@v1
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # - name: build lambda artifact
      #   run: |
      #     make build
      #     zip handler.zip ./bin/rssreaderlambda
      - name: set up terraform environment
        run: terraform -chdir=infra init
      - name: deploy infrastructure
        run: terraform -chdir=infra apply -auto-approve -var google_oauth_client_id=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }} -var google_oauth_client_secret=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
